### ISSUE TITLE
triggur lib-install.muf throwing install error

### ISSUE THREAD

**Issue by lindsayschm** [fuzzball-muck/fuzzball-muf#28]
Copied the lib-install.muf into Fuzzball 6.18. Followed all the steps. On the last one, where it says to "@install lib-install.muf", it gives the following error:
```ERROR: #0=_ver/lib-install.muf/prog points to #0, which is not a program!```

i have attempted to reset the dbref a couple times in multiple ways, to both replace the first #0 and the second #0 but to no avail. i attempted to find a fix online, only for it to point to a sourceforge page from 04/05, and the author saying that @propset-ting a variable would work, except not saying what to propset.

Can somebody please tell me what i need to alter to make this thing work?

**Comment by wyld-sw** [comment]
Assuming the dbref of lib-install.muf is #1234, this helped me bypass that error:

`@propset #0=dbref:_ver/lib-install.muf/prog:#1234`

If that doesn't solve quite everything, please let us know.

**Comment by wyld-sw** [comment]
...and it appears the program may still be expecting things to be set that aren't. Hopefully you can do what you need without this. Let us know if you can't, and we'd be happy to help with a solution.

**Comment by tanabi** [comment]
Hey guys -- if you need support here, I can look tonight after work.  @lindsayschm let me know if what Wyld gave you isn't enough, okay?

**Comment by wyld-sw** [comment]
Just to add here, it appears that the reported error (and solution) would be the same regardless of what program it tries to install. This might be a simple fix to the install program. Even with the quick fix above, one of the main variables (ltdb1) may not be set as expected. 

I haven’t yet looked at this in-depth either, let me know if I can help!

**Comment by lindsayschm** [comment]
*blinkblink*
... so i ran the @propset you gave me, wyld. It actually worked.
huh. i'm glad it worked!! it updated the link on @uninstall as well from #-1 to #166 so... it seems to have worked. Now to attempt to install the other stuff...
Thank you all very very much!!!
